[project]
name = "sdxok"
version = "1.0"
dependencies = [
  "pyside6",
  "qrcode",
  "flask",
  "colorama>=0.4.6",
  "coloredlogs>=15.0.1",
  "openpyxl",
  "pillow",
  "pytz",
  "requests>=2.32.4",
  "pytest",
  "tools",
  "pyzbar"
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
# packages å­—æ®µå‘Šè¯‰æ„å»ºç³»ç»Ÿå»å“ªé‡Œæ‰¾è¦æ‰“åŒ…å’Œå®‰è£…çš„ Python åŒ…ã€‚
# å®ƒä¼šæŒ‡ç¤ºå·¥å…·åˆ° "src" ç›®å½•ä¸‹å»æ‰¾æ‰€æœ‰éœ€è¦çš„åŒ…ã€‚
packages = ["src"]
[tool.pytest.ini_options]
# ğŸ”¥ å…³é”®ï¼šå‘Šè¯‰ Pytest åœ¨æ”¶é›†æµ‹è¯•å‰ï¼Œå°† "src" ç›®å½•æ·»åŠ åˆ° Python æœç´¢è·¯å¾„ä¸­ã€‚
pythonpath = ["src"]
# å¯ä»¥åŒæ—¶æ·»åŠ æµ‹è¯•ç›®å½•ï¼Œä»¥é˜²ä¸‡ä¸€
# pythonpath = ["src", "test"]